### ISSUE TITLE
ELVUI formating broken since wim update. double time stamps in chat, full chat names, ...

### ISSUE THREAD

**Issue by Ianni** [Legacy-of-Sylvanaar/wow-instant-messenger#79]
**Describe the bug**
When using ELvUI and WIM there are double times stamps in the chat since the last wim update:
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/471066/60e92cdb-2526-4f3e-9e76-a9036c78aceb)

This is not there if WIM is disabled. Also, the Party tag sshould be (would be) shortened to P by elvui normally. Is WIM Changing something there? 
Do I miss a config to change some behavior?

**To Reproduce**
Activate elvui and wim. have some text in guild oder party. Note, the party leader chat is fine.

**Expected behavior**
no double timestamp and full party name.

**Screenshots**
see above.

**Comment by Pazza** [comment]
@Ianni in order to fix a previous issue with Questie links, I had to rerun the message filters. Therefore this is possible, if ELVUI is using the message filters to append these time stamps. WIM has messaging formatting options, one option is to include the timestamp. See if disabling WIM's timestamps fixes the issue. Worse case, I will revert the change I made for Questie. Let me know.

**Comment by Ianni** [comment]
Hi, the DIsplay Time Stamps checkbox under general only removes time stamps in the wim whisper windows. 
The odd behavior for guild raid, group and so on remains. 

I have no idea how these filters work, and why it is not happening if  the raidleader or group leader is posting something. 
Maybe you can also reach out to the elvui devs if they can do something different?

**Comment by syncness** [comment]
I have a similar issue in SoD which is ElvUI shortens the channel name, but WIM clashes and cancels it out so the name is long again.

**Comment by Pazza** [comment]
I'll undo the change. Questie links may have to remain broken

**Comment by Evonder** [comment]
It looks like it is caused by [bc281e8](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/commit/bc281e8d6421aab91b2d985109a6c04b451d910e) and not the commit for the questie fix. I removed CensoredMessageFilter.lua from the includes.xml and it appears to be working as intended.

ElvUI is not the only addon affected either.

**Comment by Pazza** [comment]
@Evonder would you be willing to test a few things?

**Comment by Pazza** [comment]
I just installed ElvUI on Classic to test. And everything appears to be working correctly.

**Comment by Evonder** [comment]
I just tried myself on classic, ElvUI and WIM only enabled with fresh savedvars. Here is a few screenshots to show the issue reported.
![wim_elvui](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/468429/21c9c0a6-3111-4bc9-a3ef-2bf76da2e080)
![wim_elvui2](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/468429/80a2f49f-9f2e-4246-9d3d-7f220f06a40f)

As you can see, there is a double timestamp on the default chat frame. The second image shows that WIM window has no timestamp on chat messages, which is what is configured in WIM.

It appears that somewhere your modifying arg1 and then returning them to the default chat frame, rather than the unmodified original msg. At least that is my assumption.

I have looked at the source briefly, but not being familiar with the project structure nor having a lot of time have I found where the problem lies.

**Comment by Pazza** [comment]
I see... I still think the root is the patch made for Questie. Because it is running the filters twice against the messages. WIM does not modify the events FYI. it has its own processor for formatting to the WIM windows.

I'll disable that bit and you let me know if it fixes it or not. I'll pink you when I've pushed something.

**Comment by Pazza** [comment]
@Evonder an alpha build should be published soon. When you have a moment, please test to see if that fixes the problem.

**Comment by E-Tsx** [comment]
Issue is still the same on 318e1d6, commenting out CensoredMessagesFilter.lua from the xml resolves it like previous build.

**Comment by Pazza** [comment]
Thanks for clarifying... Still not sure why I can't reproduce this. I will try again. Latest version on ELvUi I assume? I downloaded a copy off their website today.

**Comment by Evonder** [comment]
Appears to be the timestamp set in CVars.
Can be set in game at Options > Social > Chat Timestamps > None

Try that

**Comment by E-Tsx** [comment]
that will get rid of double timestamps (and you wont have timestamps in guildchat) yes, but that wont fix the normally shortened  channel names.
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/97974579/1fa74387-8be5-4843-aeb8-4fc970149782)
 
Example here, 1st msg is timestamps on , the other 2 are timestamp off, the channel is normally shortened as [2]

ElvUI is 13.66 (well dev release but it's same in this case, the current version)

**Comment by Pazza** [comment]
Just FYI, I'm working on a rewrite of how chat events are handled. This should hopefully resolve the issues. This method natively fixes issues such as Questie links.

**Comment by Pazza** [comment]
I posted a beta on curse. See if that resolves the issues. Censored messages are also supported within WIM now.

**Comment by Aflixion** [comment]
The 3.11.0-beta2 build fixed it, tyty

**Comment by E-Tsx** [comment]
yeah it seems resolved here also

**Comment by Pazza** [comment]
Thanks everyone!
